package com.jdwa.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.username
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.name
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.passwd
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.ts_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private Integer tsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.t_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private Integer tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.pa_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private Integer paId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.info_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private Integer infoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.m_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.role_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.q_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private Integer qId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.cla_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private Integer claId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.reserve01
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private String reserve01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.reserve02
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private String reserve02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.reserve03
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private String reserve03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.reserve04
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private String reserve04;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_usr.reserve05
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private String reserve05;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.id
     *
     * @return the value of tb_usr.id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.id
     *
     * @param id the value for tb_usr.id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.username
     *
     * @return the value of tb_usr.username
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.username
     *
     * @param username the value for tb_usr.username
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.name
     *
     * @return the value of tb_usr.name
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.name
     *
     * @param name the value for tb_usr.name
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.passwd
     *
     * @return the value of tb_usr.passwd
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.passwd
     *
     * @param passwd the value for tb_usr.passwd
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.ts_id
     *
     * @return the value of tb_usr.ts_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public Integer getTsId() {
        return tsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.ts_id
     *
     * @param tsId the value for tb_usr.ts_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setTsId(Integer tsId) {
        this.tsId = tsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.t_id
     *
     * @return the value of tb_usr.t_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.t_id
     *
     * @param tId the value for tb_usr.t_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.pa_id
     *
     * @return the value of tb_usr.pa_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public Integer getPaId() {
        return paId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.pa_id
     *
     * @param paId the value for tb_usr.pa_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setPaId(Integer paId) {
        this.paId = paId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.info_id
     *
     * @return the value of tb_usr.info_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public Integer getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.info_id
     *
     * @param infoId the value for tb_usr.info_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setInfoId(Integer infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.m_id
     *
     * @return the value of tb_usr.m_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.m_id
     *
     * @param mId the value for tb_usr.m_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.role_id
     *
     * @return the value of tb_usr.role_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.role_id
     *
     * @param roleId the value for tb_usr.role_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.q_id
     *
     * @return the value of tb_usr.q_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public Integer getqId() {
        return qId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.q_id
     *
     * @param qId the value for tb_usr.q_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setqId(Integer qId) {
        this.qId = qId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.cla_id
     *
     * @return the value of tb_usr.cla_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public Integer getClaId() {
        return claId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.cla_id
     *
     * @param claId the value for tb_usr.cla_id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setClaId(Integer claId) {
        this.claId = claId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.reserve01
     *
     * @return the value of tb_usr.reserve01
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public String getReserve01() {
        return reserve01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.reserve01
     *
     * @param reserve01 the value for tb_usr.reserve01
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setReserve01(String reserve01) {
        this.reserve01 = reserve01 == null ? null : reserve01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.reserve02
     *
     * @return the value of tb_usr.reserve02
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public String getReserve02() {
        return reserve02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.reserve02
     *
     * @param reserve02 the value for tb_usr.reserve02
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setReserve02(String reserve02) {
        this.reserve02 = reserve02 == null ? null : reserve02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.reserve03
     *
     * @return the value of tb_usr.reserve03
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public String getReserve03() {
        return reserve03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.reserve03
     *
     * @param reserve03 the value for tb_usr.reserve03
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setReserve03(String reserve03) {
        this.reserve03 = reserve03 == null ? null : reserve03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.reserve04
     *
     * @return the value of tb_usr.reserve04
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public String getReserve04() {
        return reserve04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.reserve04
     *
     * @param reserve04 the value for tb_usr.reserve04
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setReserve04(String reserve04) {
        this.reserve04 = reserve04 == null ? null : reserve04.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_usr.reserve05
     *
     * @return the value of tb_usr.reserve05
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public String getReserve05() {
        return reserve05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_usr.reserve05
     *
     * @param reserve05 the value for tb_usr.reserve05
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setReserve05(String reserve05) {
        this.reserve05 = reserve05 == null ? null : reserve05.trim();
    }
}