package com.jdwa.pojo;

public class UserType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_type.id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_type.uid
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_type.name
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_type.info
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_type.duty
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    private String duty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_type.id
     *
     * @return the value of tb_user_type.id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_type.id
     *
     * @param id the value for tb_user_type.id
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_type.uid
     *
     * @return the value of tb_user_type.uid
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_type.uid
     *
     * @param uid the value for tb_user_type.uid
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_type.name
     *
     * @return the value of tb_user_type.name
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_type.name
     *
     * @param name the value for tb_user_type.name
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_type.info
     *
     * @return the value of tb_user_type.info
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_type.info
     *
     * @param info the value for tb_user_type.info
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_type.duty
     *
     * @return the value of tb_user_type.duty
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_type.duty
     *
     * @param duty the value for tb_user_type.duty
     *
     * @mbg.generated Fri Nov 08 23:30:40 CST 2019
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }
}